---
title: "MaxART.testscript.Rmd"
author: "Wim Delva"
date: "29 Jul 2016"
output: html_document
---

```{r, echo = FALSE, cache = FALSE, message = FALSE}
library(RSimpactCyan)
library(RSimpactHelper)
library(data.table)
library(dplyr)
library(magrittr)
library(exactci)
library(nlme)
library(ggplot2)
install.packages("readcsvcolumns", repos="http://193.190.10.42/jori/")
library(readcsvcolumns)
library(survival)
library(KMsurv)
library(tidyr)
library(expoTree)
library(sna)
library(intergraph)
library(igraph)

# MaxART specific simulation
# MaxART specific simulation
simpact.set.simulation("simpact-cyan")#("maxart")

agedist.data.frame <- agedistr.creator(shape = 5, scale = 65)

testinput <- list()
testinput$mortality.normal.weibull.shape <- 5
testinput$mortality.normal.weibull.scale <- 65
testinput$mortality.normal.weibull.genderdiff <- 0
testinput$periodiclogging.interval <- 1
testinput$syncrefyear.interval <- 1
testinput$formation.hazard.type <- "agegapry"
testinput$person.eagerness.dist.type <- "gamma"
testinput$person.eagerness.dist.type <- "gamma"
testinput$person.eagerness.dist.gamma.a <- 0.231989836885#0.15 #0.425#3.4#1.7#0.85 #0.1
testinput$person.eagerness.dist.gamma.b <- 45#70#100 #3.5#5#10#20 #170
testinput$person.agegap.man.dist.type <- "normal"
testinput$person.agegap.woman.dist.type <- "normal"
testinput$person.agegap.man.dist.normal.mu <- -5
testinput$person.agegap.woman.dist.normal.mu <- 2.5
testinput$person.agegap.man.dist.normal.sigma <- 1
testinput$person.agegap.woman.dist.normal.sigma <- 1
testinput$formation.hazard.agegapry.numrel_man <- -0.5
testinput$formation.hazard.agegapry.numrel_woman <- -0.5
testinput$formation.hazard.agegapry.gap_factor_man_exp <- -0.35#-0.15# -0.5
testinput$formation.hazard.agegapry.gap_factor_woman_exp <- -0.35#-0.15# -0.5
testinput$formation.hazard.agegapry.gap_factor_man_const <- 0
testinput$formation.hazard.agegapry.gap_factor_woman_const <- 0
testinput$formation.hazard.agegapry.gap_agescale_man <- 0.23
testinput$formation.hazard.agegapry.gap_agescale_woman <- 0.1#0.23
testinput$formation.hazard.agegapry.eagerness_sum <- 0.1
testinput$formation.hazard.agegapry.eagerness_diff <- -0.048#-0.110975
testinput$dissolution.alpha_0 <- -0.52#-0.1 # baseline
testinput$dissolution.alpha_4 <- -0.05 
testinput$debut.debutage <- 14
testinput$population.simtime <- 50
testinput$population.nummen <- 2000
testinput$population.numwomen <- 2000
testinput$population.maxevents <- testinput$population.simtime * testinput$population.nummen * 4 # If 4 events happen per person per year, something's wrong.
testinput$population.eyecap.fraction <- 0.2
testinput$hivseed.type <- "amount"
testinput$hivseed.amount <- 1#20
testinput$hivseed.age.min <- 15
testinput$hivseed.age.max <- 25
testinput$hivseed.time <- 10
testinput$transmission.param.a <- -1.0352239
testinput$transmission.param.b <- -89.339994
testinput$transmission.param.c <- 0.4948478
testinput$transmission.param.f1 <- log(5) # ~1.6 such that the hazard is x 5 in 15 yo
testinput$transmission.param.f2 <- log(log(2.5) / log(5)) / 5
testinput$conception.alpha_base <- -2.35 #-3

start.time <- proc.time()
testoutput <- simpact.run(configParams = testinput,
                          destDir = "temp",
                          agedist = agedist.data.frame,
                          seed = 3)

time.it.took <- proc.time() - start.time
time.it.took

datalist.test <- readthedata(testoutput)


# Plotting prevalence over time among 15-50 year olds (men and women combined)
prev.agegroup <- c(15, 50)
testplot.prev <- prevalence.plotter(prev.agegroup)
testplot.prev
# Plotting prevalence by age group, 30 years after introducing HIV (40 years into the simulation ~ 2017)
# 7 age groups, 2 genders, 3 types (prev, ul, ll) ==> 7*2*3 datapoints = 42 datapoints
n.rows <- 7*2*3
prevalence.at.2017 <- data.frame(agegroup = rep(NA, n.rows),
                                 gender = rep(NA, n.rows),
                                 type = rep(NA, n.rows),
                                 prevalence = rep(NA, n.rows))
row.index <- 1
for (agegroup in seq(from = 15, to = 45, by = 5)){
  for (gender in 1:2){
    for (type in 1:3){
      prevalence.at.2017$agegroup[row.index] <- paste0(agegroup," <= x < ",(agegroup+5))
      prevalence.at.2017$gender[row.index] <- c("Men", "Women")[gender]
      prevalence.at.2017$type[row.index] <- c("point.est", "ll", "ul")[type]
      prevalence.at.2017$prevalence[row.index] <- as.numeric(prevalence.calculator(datalist = datalist.test,
                                                             agegroup = c(agegroup, (agegroup+5)),
                                                             timepoint = 40)[gender, (type+3)])
      row.index <- row.index + 1
    }
  }
}
prevalence.at.2017$point.est <- prevalence.at.2017$type=="point.est"
prevalence.at.2017$gender.agegroup <- paste0(prevalence.at.2017$agegroup, prevalence.at.2017$gender)

p <- ggplot(prevalence.at.2017, aes(x=agegroup, y=prevalence, group=gender.agegroup)) +
  geom_line(aes(colour = gender), size=.6,
            position = position_dodge(width = .5)) +
  geom_point(aes(colour = gender , shape = !point.est, size = !point.est),
             position = position_dodge(width = .5)) +
  scale_shape_manual(values=c(19, 95), guide = FALSE) +
  scale_size_manual(values=c(3, 7), guide = FALSE) +
  scale_colour_brewer(palette = "Set1", direction = -1, name = "Gender") +
  xlab("Age groups") +
  ylab("HIV prevalence") +
  #facet_wrap(~Gender, nrow=1)
  theme_bw() #+
  #theme(legend.position = "none")
p

# Plotting the phylo tree
transm.ls <- transm.network.builder(datalist.test, endpoint = 12)
test.tree <- epi2tree(transm.ls)
plot(test.tree, edge.width = 2, cex = 1.5)

# Plotting the transmission network
transm.df <- data.frame(tails = as.character(transm.ls$parent),
                        heads = as.character(transm.ls$id))
tn <- network(transm.df, directed = TRUE, matrix.type = "edgelist")
plot(tn, label.cex = 1.5, mode  = "fruchtermanreingold")
tn.igraph <- asIgraph(tn)
V(tn.igraph)$name <- network.vertex.names(tn)
plot(tn.igraph, layout = layout.reingold.tilford(tn.igraph))


plot(tn, label = network.vertex.names(tn), label.cex = 1.5)
tnplot <- plot(tt$tn,
                label = "",
                vertex.col = tt$tn.vertex.col,
                vertex.cex = tt$tn.vertex.cex,
                jitter=F)


agemix.df <- agemix.df.maker(datalist.test)
sd(agemix.df$AgeGap, na.rm = TRUE)
agemix.pattern <- pattern.modeller(dataframe = agemix.df, agegroup = c(15, 60), timepoint = 50, timewindow = 1, start = FALSE)
testplot.agemix <- pattern.plotter(agemix.pattern)
testplot.agemix
incidence.calculator(datalist = datalist.test, agegroup = c(14,18), timewindow = c(40, 50))
incidence.calculator(datalist = datalist.test, agegroup = c(15,30), timewindow = c(40, 50))

degree.df <- degree.df.maker(agemix.df, agegroup = c(15, 30), hivstatus = 0, survey.time = 40, window.width = 1, only.new = TRUE)
mean(degree.df$Degree)
mean(degree.df$Degree > 1)
datalist.test$itable$person.eagerness.dist.gamma.a * datalist.test$itable$person.eagerness.dist.gamma.b

degree.hist <- degree.hist.maker(dataframe = degree.df)
degree.hist
gamma.dens <- dgamma(seq(0.1, 200, by = 0.1),
                     shape = datalist.test$itable$person.eagerness.dist.gamma.a,
                     scale = datalist.test$itable$person.eagerness.dist.gamma.b)

gamma.dens <- dgamma(seq(0.1, 200, by = 0.1),
                     shape = 3.4,
                     scale = 3.5)

plot(seq(0.1, 200, by = 0.1), gamma.dens, type = "l")

hist(datalist.test$ptable$FormEag, freq = FALSE, 200)

incidence.calculator(datalist.test, timewindow = c(40, 50))



coxph.person.df <- coxph.person.df.maker(datalist = datalist.test, agegroup = c(15, 30), timewindow = c(30, 40))
# Now we create the dataset for the CoxPH models
#1. Firstly, a dataset to do a person-level analysis
# We can treat the data as left-truncated (women must be HIV-negative at the time of entering the cohort of 15>= year old women).
# Because we assume that the study cohort's observation time starts at some arbitrary point in the simulation
# (e.g. 20 years after HIV is introduced), some women will enter the cohort at an age > 15 (but still < 30).
# time is the left-truncated age of entering the cohort
# time2 is the event time or end time of the interval if the event wasn't observed by the end of the study.
# The event parameter indicates whether or not the HIV transmission event was observed or not.
# type indicates that we have right-censored data.

# Cohort should include all the women we were at least for some period (> 0 time units) HIV-negative and between 15 and 30 years old.

Surv(time = age, time2 = age + time, event = observed, type = "right")


#2. Secondly, a dataset to do a relationship-level analysis

agemix.df <- agemix.df.maker(datalist.test) %>% subset(Gender == "female")
degree.df <- degree.df.maker(df = agemix.df, survey.time = 20, window.width = 1, only.new = TRUE)
Degree.LT.one <- sum(degree.df$Degree > 1) / length(degree.df$Degree)
incidence.df <- incidence.calculator(datalist = datalist.test, agegroup = c(15, 30), timewindow = c(19, 20))
inc <- incidence.df$incidence[2]
prevalence.calculator(datalist = datalist.test, agegroup = c(15, 50), timepoint = 20)
ART.coverage.calculator(datalist = datalist.test, agegroup = c(15, 50), timepoint = 20)
pop.growth.calculator(datalist = datalist.test, timewindow = c(0, 20))

print(c(Degree.LT.one, inc))





V <- c(1e3, 1e4, 1e5, 1e6)
transmission.param.a <- -1.0352239 #-1.3997
transmission.param.b <- -89.339994 #-12.0220
transmission.param.c <- 0.4948478 #0.1649
transmission.param.f1 <- log(5)

trans.hazard <- exp(transmission.param.a +
      transmission.param.b * V^-transmission.param.c +
        transmission.param.f1)
log10(100 * trans.hazard)

agedist.data.frame <- agedistr.creator(shape = 5, scale = 65)
testinput <- input.params.creator(conception.alpha_base = -2,
                                  population.eyecap.fraction = 1,
                                  population.simtime = 20,
                                  population.numwomen = 1000,
                                  population.nummen = 1000,
                                  hivseed.amount = 20,
                                  hivseed.age.min = 15,
                                  hivseed.age.max = 75,
                                  person.agegap.woman.dist.normal.sigma = 1,
                                  person.agegap.man.dist.normal.sigma = 1,
                                  person.eagerness.dist.gamma.b = 50,
                                  formation.hazard.agegapry.gap_factor_woman_exp = -0.5,
                                  formation.hazard.agegapry.gap_factor_man_exp = -0.5,
                                  transmission.param.a = -1.0352239, #-1.3997
                                  transmission.param.b = -89.339994, #-12.0220
                                  transmission.param.c = 0.4948478, #0.1649
                                  transmission.param.f1 = log(5),
                                  transmission.param.f2 = 0,
                                  person.vsp.toacute.x = 10,
                                  person.vsp.toaids.x = 7,
                                  person.vsp.tofinalaids.x = 12
                                  )

testinput$transmission.param.f1 <- log(5)
testinput$population.nummen <- 500
testinput$population.numwomen <- 500
testinput$population.simtime <- 30
testinput$conception.alpha_base <- -2
testinput$hivseed.age.min <- 25
testinput$hivseed.age.max <- 50
testinput$person.agegap.man.dist.type <- "normal"
testinput$person.agegap.woman.dist.type <- "normal"
testinput$person.agegap.woman.dist.normal.sigma <- 1
testinput$person.agegap.man.dist.normal.sigma <- 1
testinput$person.agegap.woman.dist.normal.mu <- -4
testinput$person.agegap.man.dist.normal.mu <- -4


testinput$formation.hazard.agegapry.gap_factor_woman_exp <- -0.5#-0.5
testinput$formation.hazard.agegapry.gap_factor_man_exp <- -0.5#-0.5
testoutput <- simpact.run(configParams = testinput,
                          destDir = "temp",
                          agedist = agedist.data.frame,
                          seed = 11)
datalist.test <- readthedata(testoutput)


transmission.events <- subset(datalist.test$etable, eventname == "transmission")
table(transmission.events$p1gender)
hist(datalist.test$rtable$AgeGap)

times <- 0:30

# Calculating HIV prevalence over time
prev.df <- data.frame(times = times,
                      prevalence.men = NA,
                      prevalence.women = NA,
                      prevalence.all = NA)
row.number <- 1
for (time.point in times){
  prevalence.df <- prevalence.calculator(datalist = datalist.test,
                                         agegroup = c(15, 50),
                                         timepoint = time.point)
  prev.df[row.number, ] <- c(time.point, prevalence.df$pointprevalence)
  row.number <- row.number + 1
}


matplot(x = prev.df$times,
        y = prev.df[, 2:4],
        type = "s")
legend(x = "bottomright",
       col = 1:3,
       lty = rep(1, 4),
       legend = c("Men", "Women", "Both"))


# Calculating age mixing metrics at the end of the simulation
agemix.df <- agedif.metric.calculator(datalist = datalist.test,
                                      agegroup = c(15, 30),
                                      timewindow = 10,
                                      timepoint = 15)

agemix.df

# Calculating HIV incidence over time

#' incidence.df <- incidence.calculator(datalist = datalist, agegroup = c(15, 30), timewindow = c(20, 30))
inc.df <- data.frame(times = NA,
                     incidence.men = NA,
                     incidence.women = NA,
                     incidence.all = NA)
row.number <- 1
for (time.point in times[-length(times)]){
  incidence.df <- incidence.calculator(datalist = datalist.test,
                                       agegroup = c(15, 50),
                                       timewindow = c(time.point, time.point + 1))
  inc.df[row.number, ] <- c(time.point + 1, incidence.df$incidence)
  row.number <- row.number + 1
}

matplot(x = inc.df$times,
        y = inc.df[, 2:4],
        type = "s",
        xlab = "time (years)",
        ylab = "HIV incidence",
        main = "transmission.param.f1 = 0")
legend(x = "bottomright",
       col = 1:3,
       lty = rep(1, 4),
       legend = c("Men", "Women", "Both"))




###
###

testinput <- input.params.creator(conception.alpha_base = -2,
                                  population.eyecap.fraction = 0.4,
                                  population.simtime = 30,
                                  population.numwomen = 1000,
                                  population.nummen = 1000,
                                  hivseed.amount = 20,
                                  hivseed.age.min = 15,
                                  hivseed.age.max = 55,
                                  person.agegap.woman.dist.normal.sigma = 1,
                                  person.agegap.man.dist.normal.sigma = 1,
                                  person.eagerness.dist.gamma.b = 40,
                                  formation.hazard.agegapry.gap_factor_woman_exp = -0.5,
                                  formation.hazard.agegapry.gap_factor_man_exp = -0.5,
                                  transmission.param.f1 = 5,
                                  transmission.param.f2 = 0,
                                  person.vsp.toacute.x = 1,
                                  person.vsp.toaids.x = 1,
                                  person.vsp.tofinalaids.x = 1
                                  )
testoutput <- simpact.run(configParams = testinput,
                          destDir = "temp",
                          agedist = agedist.data.frame,
                          seed = 1)
datalist.test <- readthedata(testoutput)
times <- 0:30

# Calculating HIV incidence over time

#' incidence.df <- incidence.calculator(datalist = datalist, agegroup = c(15, 30), timewindow = c(20, 30))
inc.df <- data.frame(times = NA,
                     incidence.men = NA,
                     incidence.women = NA,
                     incidence.all = NA)
row.number <- 1
for (time.point in times[-length(times)]){
  incidence.df <- incidence.calculator(datalist = datalist.test,
                                       agegroup = c(15, 50),
                                       timewindow = c(time.point, time.point + 1))
  inc.df[row.number, ] <- c(time.point + 1, incidence.df$incidence)
  row.number <- row.number + 1
}

matplot(x = inc.df$times,
        y = inc.df[, 2:4],
        type = "s",
        xlab = "time (years)",
        ylab = "HIV incidence",
        main = "transmission.param.f1 = 5")
legend(x = "bottomright",
       col = 1:3,
       lty = rep(1, 4),
       legend = c("Men", "Women", "Both"))



###
###

testinput <- input.params.creator(conception.alpha_base = -2,
                                  population.eyecap.fraction = 0.4,
                                  population.simtime = 30,
                                  population.numwomen = 1000,
                                  population.nummen = 1000,
                                  hivseed.amount = 20,
                                  hivseed.age.min = 15,
                                  hivseed.age.max = 25,
                                  person.agegap.woman.dist.normal.sigma = 1,
                                  person.agegap.man.dist.normal.sigma = 1,
                                  person.eagerness.dist.gamma.b = 40,
                                  formation.hazard.agegapry.gap_factor_woman_exp = -0.5,
                                  formation.hazard.agegapry.gap_factor_man_exp = -0.5,
                                  transmission.param.f1 = -100,
                                  transmission.param.f2 = 0,
                                  person.vsp.toacute.x = 1,
                                  person.vsp.toaids.x = 1,
                                  person.vsp.tofinalaids.x = 1
                                  )
testoutput <- simpact.run(configParams = testinput,
                          destDir = "temp",
                          agedist = agedist.data.frame,
                          seed = 1)
datalist.test <- readthedata(testoutput)
times <- 0:30

# Calculating HIV incidence over time

#' incidence.df <- incidence.calculator(datalist = datalist, agegroup = c(15, 30), timewindow = c(20, 30))
inc.df <- data.frame(times = times,
                     incidence.men = NA,
                     incidence.women = NA,
                     incidence.all = NA)
row.number <- 1
for (time.point in times[-length(times)]){
  incidence.df <- incidence.calculator(datalist = datalist.test,
                                       agegroup = c(15, 50),
                                       timewindow = c(time.point, time.point + 1))
  inc.df[row.number, ] <- c(time.point + 1, incidence.df$incidence)
  row.number <- row.number + 1
}

matplot(x = inc.df$times,
        y = inc.df[, 2:4],
        type = "s",
        xlab = "time (years)",
        ylab = "HIV incidence",
        main = "transmission.param.f1 = -100")
legend(x = "bottomright",
       col = 1:3,
       lty = rep(1, 4),
       legend = c("Men", "Women", "Both"))

matplot(x = prev.df$times,
        y = prev.df[, 2:4],
        type = "s",
        xlab = "time (years)",
        ylab = "HIV prevalence")
legend(x = "bottomright",
       col = 1:3,
       lty = rep(1, 4),
       legend = c("Men", "Women", "Both"))

agemix.df
hist(datalist.test$rtable$AgeGap)
print(datalist.test$ltable)
nrow(datalist.test$rtable) # Total number of relationships


```

```{r, echo = FALSE, cache = FALSE, message = FALSE}
# library(RSimpactHelper)
# library(data.table)
# library(dplyr)
# library(magrittr)
# datalist.test <- readthedata(testoutput)
# times <- 0:60
# prev.df <- data.frame(times = times,
#                       prevalence.men = NA,
#                       prevalence.women = NA,
#                       prevalence.all = NA)
# row.number <- 1
# for (times in times){
#   prevalence.df <- prevalence.calculator(datalist = datalist.test,
#                                          agegroup = c(15, 50),
#                                          timepoint = times)
#   prev.df[row.number, ] <- c(times, prevalence.df$pointprevalence)
#   row.number <- row.number + 1
# }
# 
# agemix.df <- agedif.metric.calculator(datalist = datalist.test,
#                                       agegroup = c(15, 30),
#                                       timewindow = 10,
#                                       timepoint = 30)
# 
# 
# 
# matplot(x = prev.df$times,
#         y = prev.df[, 2:4],
#         type = "s")
# legend(x = "bottomright",
#        col = 1:3,
#        lty = rep(1, 4),
#        legend = c("Men", "Women", "Both"))
# 
# agemix.df
# hist(datalist.test$rtable$AgeGap)
# print(datalist.test$ltable)
# nrow(datalist.test$rtable) # Total number of relationships
```
