#!/bin/bash -l
#
#PBS -N simpact.wrapper.easyABC.run.1
#PBS -P CBBI0949
#PBS -q normal
#PBS -l select=2:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -l walltime=00:10:00
#PBS -m be
#BPS -M trust@aims.ac.za

source /home/tchibawara/SimpactCyanBuild/simpactpack/bin/activatesimpact.sh

ulimit -s unlimited

module add /apps/chpc/scripts/modules/bio/app/simpact-cyan/0.21.0

cd /mnt/lustre/users/tchibawara/MaxART/code/

Rscript simpact.wrapper.easyABC.run.R
